- name: configure frontend server
  become: yes
  hosts : frontend
  vars:
    login_host: db.hemanth78s.online
    login_password: ExpenseApp@1

  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx 
      state: latest 
  
  - name: start and enable
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes

  - name: delete defult files
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: create html
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory
